In [12]:
import numpy as np
import pandas as pd
df = pd.read_excel("C:/Users/abhij/OneDrive/Documents/Anu_Guvi/Project2/OLA_DataSet.xlsx")

In [ ]:
#As raw data file has >1 sheet of data, merging is essential for Vehicle image column
#Merging of 2 sheets in .excel file to fill the data of vehicle images column
import pandas as pd
import numpy as np # Make sure numpy is imported for NaN handling

# --- Step 1: Load the main ride data from the 'July' sheet ---
# This remains the same.
df = pd.read_excel("C:/Users/abhij/OneDrive/Documents/Anu_Guvi/Project2/OLA_DataSet.xlsx", sheet_name='July')

print("\n--- Initial Load Check for 'July' sheet ---")
print(df.info())
print("\nSample from 'July' sheet (check Vehicle Images column here - it should still be empty for now):")
print(df[['Booking_ID', 'Vehicle_Type', 'Vehicle Images']].head())


# --- Step 2: Load the vehicle image links from 'Sheet2' (without a header) ---
# Use header=None to tell pandas that the first row is not a header.
df_images = pd.read_excel("C:/Users/abhij/OneDrive/Documents/Anu_Guvi/Project2/OLA_DataSet.xlsx", sheet_name='Sheet2', header=None)

# IMPORTANT: Inspect df_images.head() to confirm column indices (0, 1, etc.)
# If your Vehicle Type is NOT in column 0, and Image Link is NOT in column 1,
# you MUST adjust the rename and merge parts below.
print("\n--- Initial Load Check for 'Sheet2' (Vehicle Images) ---")
print(df_images.info())
print("\nSample from 'Sheet2' (CHECK COLUMN INDICES HERE):")
print(df_images.head())


# --- Step 3: Rename columns in df_images and Merge into the main DataFrame (df) ---
# Rename the columns to something meaningful based on your verification in Step 2.
# Assuming column 0 is 'Vehicle_Type' and column 1 is 'Vehicle Images' (the link itself).
df_images.rename(columns={0: 'Vehicle_Type', 1: 'Vehicle Images'}, inplace=True)

# Drop duplicate rows in df_images if a Vehicle_Type appears multiple times with different links
# (e.g., if 'Sheet2' has multiple links for 'Mini', decide which one to keep, or average/list them)
# For simplicity, we'll assume each Vehicle_Type has a unique primary image.
df_images.drop_duplicates(subset=['Vehicle_Type'], inplace=True)


# The 'Vehicle Images' column in df (from 'July' sheet) is currently empty/NaN.
# We will drop it and then merge the correct 'Vehicle Images' from df_images.
df.drop(columns=['Vehicle Images'], inplace=True, errors='ignore')

# Perform the merge. We'll left merge to keep all original ride data.
df = pd.merge(df, df_images[['Vehicle_Type', 'Vehicle Images']], on='Vehicle_Type', how='left')


print("\n--- DataFrame Info After Merging Vehicle Images ---")
print(df.info())
print("\nSample of Vehicle Images column after merge (should now have links):")
print(df[['Booking_ID', 'Vehicle_Type', 'Vehicle Images']].head())

# --- NOW, YOU CAN PASTE THE ENTIRE CONSOLIDATED DATA CLEANING & FEATURE ENGINEERING BLOCK HERE ---
# (The one I provided in the previous turn, including all fillna, timestamp creation,
# boolean flags, and category conversions.)

# After the consolidated cleaning block, re-run your final checks:
# print("\n--- Final df.isnull().sum() after full cleaning ---")
# print(df.isnull().sum())

# print("\n--- Final df.info() after full cleaning ---")
# print(df.info())

--- Initial Load Check for 'July' sheet ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              0 non-null       float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(12)
memory usage: 15.7+ MB
None

Sample from 'July' sheet (check Vehicle Images column here - it should still be empty for now):
      Booking_ID Vehicle_Type  Vehicle Images
0  CNR7153255142  Prime Sedan             NaN
1  CNR2940424040         Bike             NaN
2  CNR2982357879    Prime SUV             NaN
3  CNR2395710036        eBike             NaN
4  CNR1797421769         Mini             NaN

--- Initial Load Check for 'Sheet2' (Vehicle Images) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7 non-null      object
 1   1       7 non-null      object
dtypes: object(2)
memory usage: 260.0+ bytes
None

Sample from 'Sheet2' (CHECK COLUMN INDICES HERE):
             0                                                  1
0          NaN                                                NaN
1  Prime Sedan  https://cdn-icons-png.flaticon.com/128/14183/1...
2         Bike  https://cdn-icons-png.flaticon.com/128/9983/99...
3    Prime SUV  https://cdn-icons-png.flaticon.com/128/9983/99...
4        eBike  https://cdn-icons-png.flaticon.com/128/6839/68...

--- DataFrame Info After Merging Vehicle Images ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(13)
memory usage: 15.7+ MB
None

Sample of Vehicle Images column after merge (should now have links):
      Booking_ID Vehicle_Type  \
0  CNR7153255142  Prime Sedan
1  CNR2940424040         Bike
2  CNR2982357879    Prime SUV
3  CNR2395710036        eBike
4  CNR1797421769         Mini

                                      Vehicle Images
0  https://cdn-icons-png.flaticon.com/128/14183/1...
1  https://cdn-icons-png.flaticon.com/128/9983/99...
2  https://cdn-icons-png.flaticon.com/128/9983/99...
3  https://cdn-icons-png.flaticon.com/128/6839/68...
4  https://cdn-icons-png.flaticon.com/128/3202/32...

In [ ]:
df.head()
df.info()

In [ ]:
print("\n--- Initial Load Check for Vehicle Images ---")
print("Initial non-null count for 'Vehicle Images':", df['Vehicle Images'].count())
print("Initial sample values from 'Vehicle Images':")
print(df['Vehicle Images'].head())

--- Initial Load Check for Vehicle Images ---
Initial non-null count for 'Vehicle Images': 103024
Initial sample values from 'Vehicle Images':
0    https://cdn-icons-png.flaticon.com/128/14183/1...
1    https://cdn-icons-png.flaticon.com/128/9983/99...
2    https://cdn-icons-png.flaticon.com/128/9983/99...
3    https://cdn-icons-png.flaticon.com/128/6839/68...
4    https://cdn-icons-png.flaticon.com/128/3202/32...
Name: Vehicle Images, dtype: object

In [ ]:
print("\n--- Vehicle Images Column Check ---")
print("Data type of 'Vehicle Images':", df['Vehicle Images'].dtype)
print("Non-null count for 'Vehicle Images':", df['Vehicle Images'].count())
print("\nSample values from 'Vehicle Images':")
print(df['Vehicle Images'].head())

In [19]:
#Checking if image links are correctly placed for right vehicle type 
df[['Booking_ID', 'Vehicle_Type', 'Vehicle Images']].head()

,Booking_ID,Vehicle_Type,Vehicle Images
0,CNR7153255142,Prime Sedan,https://cdn-icons-png.flaticon.com/128/14183/1...
1,CNR2940424040,Bike,https://cdn-icons-png.flaticon.com/128/9983/99...
2,CNR2982357879,Prime SUV,https://cdn-icons-png.flaticon.com/128/9983/99...
3,CNR2395710036,eBike,https://cdn-icons-png.flaticon.com/128/6839/68...
4,CNR1797421769,Mini,https://cdn-icons-png.flaticon.com/128/3202/32...

In [20]:

# Display info and first few rows after cleaning
print("\n--- DataFrame Info before Cleaning ---")
df.info()

--- DataFrame Info before Cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(13)
memory usage: 15.7+ MB

In [21]:
print("\n--- First 5 Rows before Cleaning ---")
print(df.head())

--- First 5 Rows before Cleaning ---
                 Date      Time     Booking_ID        Booking_Status  \
0 2024-07-26 14:00:00  14:00:00  CNR7153255142    Canceled by Driver
1 2024-07-25 22:20:00  22:20:00  CNR2940424040               Success
2 2024-07-30 19:59:00  19:59:00  CNR2982357879               Success
3 2024-07-22 03:15:00  03:15:00  CNR2395710036  Canceled by Customer
4 2024-07-02 09:02:00  09:02:00  CNR1797421769               Success

  Customer_ID Vehicle_Type Pickup_Location Drop_Location  V_TAT  C_TAT  \
0   CID713523  Prime Sedan     Tumkur Road      RT Nagar    NaN    NaN
1   CID225428         Bike     Magadi Road       Varthur  203.0   30.0
2   CID270156    Prime SUV   Sahakar Nagar       Varthur  238.0  130.0
3   CID581320        eBike      HSR Layout   Vijayanagar    NaN    NaN
4   CID939555         Mini     Rajajinagar   Chamarajpet  252.0   80.0

                     Canceled_Rides_by_Customer      Canceled_Rides_by_Driver  \
0                                           NaN  Personal & Car related issue
1                                           NaN                           NaN
2                                           NaN                           NaN
3  Driver is not moving towards pickup location                           NaN
4                                           NaN                           NaN

  Incomplete_Rides Incomplete_Rides_Reason  Booking_Value Payment_Method  \
0              NaN                     NaN            444            NaN
1               No                     NaN            158           Cash
2               No                     NaN            386            UPI
3              NaN                     NaN            384            NaN
4               No                     NaN            822    Credit Card

   Ride_Distance  Driver_Ratings  Customer_Rating  \
0              0             NaN              NaN
1             13             4.1              4.0
2             40             4.2              4.8
3              0             NaN              NaN
4             45             4.0              3.0

                                      Vehicle Images
0  https://cdn-icons-png.flaticon.com/128/14183/1...
1  https://cdn-icons-png.flaticon.com/128/9983/99...
2  https://cdn-icons-png.flaticon.com/128/9983/99...
3  https://cdn-icons-png.flaticon.com/128/6839/68...
4  https://cdn-icons-png.flaticon.com/128/3202/32...

In [22]:
print("\n--- Missing Values Count before Cleaning ---")
print(df.isnull().sum())

--- Missing Values Count before Cleaning ---
Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [23]:
# --- CONSOLIDATED DATA CLEANING & FEATURE ENGINEERING ---

# 1. Handle Missing Values in Categorical Columns
# Fill NaN with specific placeholder strings based on context
df['Canceled_Rides_by_Customer'].fillna('Not Canceled by Customer', inplace=True)
df['Canceled_Rides_by_Driver'].fillna('Not Canceled by Driver', inplace=True)
df['Incomplete_Rides_Reason'].fillna('Not Incomplete', inplace=True)
df['Payment_Method'].fillna('Unknown', inplace=True)
# For 'Incomplete_Rides', fill NaN with 'No' as per previous discussion, assuming 0/No means not incomplete
df['Incomplete_Rides'].fillna('No', inplace=True)


# 2. Handle Missing Values in Numeric Columns
# Convert to numeric, leaving NaN if present, or fill with 0 if that's desired for calculations
df['V_TAT'] = pd.to_numeric(df['V_TAT'], errors='coerce')
df['C_TAT'] = pd.to_numeric(df['C_TAT'], errors='coerce')
df['Driver_Ratings'] = pd.to_numeric(df['Driver_Ratings'], errors='coerce')
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'], errors='coerce')

# Optional: If you want to fill these NaNs with 0 instead of leaving them as NaN
# df['V_TAT'].fillna(0, inplace=True)
# df['C_TAT'].fillna(0, inplace=True)
# df['Driver_Ratings'].fillna(0, inplace=True)
# df['Customer_Rating'].fillna(0, inplace=True)


# 3. Convert and combine Date and Time to a single Timestamp column
# Ensure 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
# Convert 'Time' column to string format for concatenation
df['Time_Str'] = df['Time'].astype(str)
# Combine Date and Time as strings and convert to datetime
df['Timestamp'] = pd.to_datetime(df['Date'].dt.strftime('%Y-%m-%d') + ' ' + df['Time_Str'], errors='coerce')

# Drop original 'Date', 'Time', 'Time_Str' columns and 'Time_Delta' if it was created temporarily
# Ensure Time_Delta is dropped if it somehow persists as a temporary column from previous attempts
df = df.drop(columns=['Date', 'Time', 'Time_Str'], errors='ignore') # 'errors=ignore' prevents error if column already dropped
if 'Time_Delta' in df.columns:
    df = df.drop(columns=['Time_Delta'])


# 4. Extract temporal features from 'Timestamp'
df['Hour_of_Day'] = df['Timestamp'].dt.hour
df['Day_of_Week'] = df['Timestamp'].dt.day_name()
df['Month'] = df['Timestamp'].dt.month_name()
df['Day_of_Month'] = df['Timestamp'].dt.day
df['Weekday_Weekend'] = df['Timestamp'].dt.weekday.apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')


# 5. Create CORRECTED boolean flags for ride status
# Base these directly on Booking_Status for clarity and accuracy
df['Is_Canceled'] = (df['Booking_Status'].isin(['Canceled by Customer', 'Canceled by Driver', 'Driver Not Found']))
df['Is_Customer_Canceled'] = (df['Booking_Status'] == 'Canceled by Customer')
df['Is_Driver_Canceled'] = (df['Booking_Status'] == 'Canceled by Driver')
df['Is_Incomplete'] = (df['Incomplete_Rides'] == 'Yes') # Assuming 'Yes' in Incomplete_Rides means incomplete


# 6. Convert relevant object columns to 'category' dtype for memory efficiency
categorical_cols = [
    'Booking_Status', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location',
    'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides',
    'Incomplete_Rides_Reason', 'Payment_Method', 'Day_of_Week', 'Month',
    'Weekday_Weekend'
]

for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

# --- END OF CONSOLIDATED DATA CLEANING & FEATURE ENGINEERING ---

# After this block, you can then add your df.info(), df.head() and df.to_csv() calls
print("\n--- DataFrame Info After Re-Cleaning & Feature Engineering ---")
df.info()

print("\n--- First 5 Rows After Re-Cleaning & Feature Engineering ---")
print(df.head())

C:\Users\abhij\AppData\Local\Temp\ipykernel_15596\3707933285.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Canceled_Rides_by_Customer'].fillna('Not Canceled by Customer', inplace=True)
C:\Users\abhij\AppData\Local\Temp\ipykernel_15596\3707933285.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Canceled_Rides_by_Driver'].fillna('Not Canceled by Driver', inplace=True)
C:\Users\abhij\AppData\Local\Temp\ipykernel_15596\3707933285.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Incomplete_Rides_Reason'].fillna('Not Incomplete', inplace=True)
C:\Users\abhij\AppData\Local\Temp\ipykernel_15596\3707933285.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Method'].fillna('Unknown', inplace=True)
C:\Users\abhij\AppData\Local\Temp\ipykernel_15596\3707933285.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Incomplete_Rides'].fillna('No', inplace=True)

--- DataFrame Info After Re-Cleaning & Feature Engineering ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Booking_ID                  103024 non-null  object
 1   Booking_Status              103024 non-null  category
 2   Customer_ID                 103024 non-null  object
 3   Vehicle_Type                103024 non-null  category
 4   Pickup_Location             103024 non-null  category
 5   Drop_Location               103024 non-null  category
 6   V_TAT                       63967 non-null   float64
 7   C_TAT                       63967 non-null   float64
 8   Canceled_Rides_by_Customer  103024 non-null  category
 9   Canceled_Rides_by_Driver    103024 non-null  category
 10  Incomplete_Rides            103024 non-null  category
 11  Incomplete_Rides_Reason     103024 non-null  category
 12  Booking_Value               103024 non-null  int64
 13  Payment_Method              103024 non-null  category
 14  Ride_Distance               103024 non-null  int64
 15  Driver_Ratings              63967 non-null   float64
 16  Customer_Rating             63967 non-null   float64
 17  Vehicle Images              103024 non-null  object
 18  Timestamp                   103024 non-null  datetime64[ns]
 19  Hour_of_Day                 103024 non-null  int32
 20  Day_of_Week                 103024 non-null  category
 21  Month                       103024 non-null  category
 22  Day_of_Month                103024 non-null  int32
 23  Weekday_Weekend             103024 non-null  category
 24  Is_Canceled                 103024 non-null  bool
 25  Is_Customer_Canceled        103024 non-null  bool
 26  Is_Driver_Canceled          103024 non-null  bool
 27  Is_Incomplete               103024 non-null  bool
dtypes: bool(4), category(12), datetime64[ns](1), float64(4), int32(2), int64(2), object(3)
memory usage: 10.2+ MB

--- First 5 Rows After Re-Cleaning & Feature Engineering ---
      Booking_ID        Booking_Status Customer_ID Vehicle_Type  \
0  CNR7153255142    Canceled by Driver   CID713523  Prime Sedan
1  CNR2940424040               Success   CID225428         Bike
2  CNR2982357879               Success   CID270156    Prime SUV
3  CNR2395710036  Canceled by Customer   CID581320        eBike
4  CNR1797421769               Success   CID939555         Mini

  Pickup_Location Drop_Location  V_TAT  C_TAT  \
0     Tumkur Road      RT Nagar    NaN    NaN
1     Magadi Road       Varthur  203.0   30.0
2   Sahakar Nagar       Varthur  238.0  130.0
3      HSR Layout   Vijayanagar    NaN    NaN
4     Rajajinagar   Chamarajpet  252.0   80.0

                     Canceled_Rides_by_Customer      Canceled_Rides_by_Driver  \
0                      Not Canceled by Customer  Personal & Car related issue
1                      Not Canceled by Customer        Not Canceled by Driver
2                      Not Canceled by Customer        Not Canceled by Driver
3  Driver is not moving towards pickup location        Not Canceled by Driver
4                      Not Canceled by Customer        Not Canceled by Driver

   ...           Timestamp Hour_of_Day  Day_of_Week Month  Day_of_Month  \
0  ... 2024-07-26 14:00:00          14       Friday  July            26
1  ... 2024-07-25 22:20:00          22     Thursday  July            25
2  ... 2024-07-30 19:59:00          19      Tuesday  July            30
3  ... 2024-07-22 03:15:00           3       Monday  July            22
4  ... 2024-07-02 09:02:00           9      Tuesday  July             2

   Weekday_Weekend  Is_Canceled Is_Customer_Canceled Is_Driver_Canceled  \
0          Weekday         True                False               True
1          Weekday        False                False              False
2          Weekday        False                False              False
3          Weekday         True                 True              False
4          Weekday        False                False              False

   Is_Incomplete
0          False
1          False
2          False
3          False
4          False

[5 rows x 28 columns]

In [ ]:

# Display info and first few rows after cleaning
print("\n--- DataFrame Info After Cleaning ---")
df.info()

In [25]:
print("\n--- First 5 Rows After Cleaning ---")
print(df.head())

--- First 5 Rows After Cleaning ---
      Booking_ID        Booking_Status Customer_ID Vehicle_Type  \
0  CNR7153255142    Canceled by Driver   CID713523  Prime Sedan
1  CNR2940424040               Success   CID225428         Bike
2  CNR2982357879               Success   CID270156    Prime SUV
3  CNR2395710036  Canceled by Customer   CID581320        eBike
4  CNR1797421769               Success   CID939555         Mini

  Pickup_Location Drop_Location  V_TAT  C_TAT  \
0     Tumkur Road      RT Nagar    NaN    NaN
1     Magadi Road       Varthur  203.0   30.0
2   Sahakar Nagar       Varthur  238.0  130.0
3      HSR Layout   Vijayanagar    NaN    NaN
4     Rajajinagar   Chamarajpet  252.0   80.0

                     Canceled_Rides_by_Customer      Canceled_Rides_by_Driver  \
0                      Not Canceled by Customer  Personal & Car related issue
1                      Not Canceled by Customer        Not Canceled by Driver
2                      Not Canceled by Customer        Not Canceled by Driver
3  Driver is not moving towards pickup location        Not Canceled by Driver
4                      Not Canceled by Customer        Not Canceled by Driver

   ...           Timestamp Hour_of_Day  Day_of_Week Month  Day_of_Month  \
0  ... 2024-07-26 14:00:00          14       Friday  July            26
1  ... 2024-07-25 22:20:00          22     Thursday  July            25
2  ... 2024-07-30 19:59:00          19      Tuesday  July            30
3  ... 2024-07-22 03:15:00           3       Monday  July            22
4  ... 2024-07-02 09:02:00           9      Tuesday  July             2

   Weekday_Weekend  Is_Canceled Is_Customer_Canceled Is_Driver_Canceled  \
0          Weekday         True                False               True
1          Weekday        False                False              False
2          Weekday        False                False              False
3          Weekday         True                 True              False
4          Weekday        False                False              False

   Is_Incomplete
0          False
1          False
2          False
3          False
4          False

[5 rows x 28 columns]

In [26]:
print("\n--- Missing Values Count After Cleaning ---")
print(df.isnull().sum())

--- Missing Values Count After Cleaning ---
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
Timestamp                         0
Hour_of_Day                       0
Day_of_Week                       0
Month                             0
Day_of_Month                      0
Weekday_Weekend                   0
Is_Canceled                       0
Is_Customer_Canceled              0
Is_Driver_Canceled                0
Is_Incomplete                     0
dtype: int64

In [ ]:
print("\n--- Vehicle Images Column Check ---")
print("Data type of 'Vehicle Images':", df['Vehicle Images'].dtype)
print("Non-null count for 'Vehicle Images':", df['Vehicle Images'].count())
print("\nSample values from 'Vehicle Images':")
print(df['Vehicle Images'].head())

--- Vehicle Images Column Check ---
Data type of 'Vehicle Images': object
Non-null count for 'Vehicle Images': 103024

Sample values from 'Vehicle Images':
0    https://cdn-icons-png.flaticon.com/128/14183/1...
1    https://cdn-icons-png.flaticon.com/128/9983/99...
2    https://cdn-icons-png.flaticon.com/128/9983/99...
3    https://cdn-icons-png.flaticon.com/128/6839/68...
4    https://cdn-icons-png.flaticon.com/128/3202/32...
Name: Vehicle Images, dtype: object

In [29]:
# Export the cleaned DataFrame to a CSV file
# We'll use index=False to prevent pandas from writing the DataFrame index as a column in the CSV
try:
    df.to_csv('ola_cleaned_data2.csv', index=False)
    print("DataFrame successfully exported to 'ola_cleaned_data.csv'")
except Exception as e:
    print(f"An error occurred during CSV export: {e}")

''' Other way to export file
df.to_csv('ola_cleaned_data2.csv', index=False)
print("DataFrame successfully re-exported to 'ola_cleaned_data.csv'")
'''

DataFrame successfully exported to 'ola_cleaned_data.csv'

' Other way to export file\ndf.to_csv(\'ola_cleaned_data2.csv\', index=False)\nprint("DataFrame successfully re-exported to \'ola_cleaned_data.csv\'")\n'

In [ ]:
def data_to_sql(df,ola_rides):

    from sqlalchemy import create_engine
    
    database_url = 'mysql://root:@localhost:3306/ola'
    engine = create_engine(database_url)
    df.to_sql(name="ola_rides", con=engine, if_exists='append', index=False)
    engine.dispose()

In [30]:
from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root:God%40%239999@localhost/ola", echo=True)

In [31]:
import pandas as pd
df = pd.read_csv("ola_cleaned_data2.csv")
df.head()

,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,...,Timestamp,Hour_of_Day,Day_of_Week,Month,Day_of_Month,Weekday_Weekend,Is_Canceled,Is_Customer_Canceled,Is_Driver_Canceled,Is_Incomplete
0,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,Not Canceled by Customer,Personal & Car related issue,...,2024-07-26 14:00:00,14,Friday,July,26,Weekday,True,False,True,False
1,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,Not Canceled by Customer,Not Canceled by Driver,...,2024-07-25 22:20:00,22,Thursday,July,25,Weekday,False,False,False,False
2,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Not Canceled by Customer,Not Canceled by Driver,...,2024-07-30 19:59:00,19,Tuesday,July,30,Weekday,False,False,False,False
3,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,Not Canceled by Driver,...,2024-07-22 03:15:00,3,Monday,July,22,Weekday,True,True,False,False
4,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Not Canceled by Customer,Not Canceled by Driver,...,2024-07-02 09:02:00,9,Tuesday,July,2,Weekday,False,False,False,False

In [32]:
#inserting data into ola_rides_tbl table
df.to_sql(name="ola_rides_tbl2", con=engine, if_exists='append', index=False)

2025-07-17 00:34:35,771 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2025-07-17 00:34:35,772 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-07-17 00:34:35,774 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2025-07-17 00:34:35,774 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-07-17 00:34:35,775 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2025-07-17 00:34:35,775 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-07-17 00:34:35,776 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-17 00:34:35,791 INFO sqlalchemy.engine.Engine DESCRIBE `ola`.`ola_rides_tbl2`
2025-07-17 00:34:35,792 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-07-17 00:34:35,796 INFO sqlalchemy.engine.Engine
CREATE TABLE ola_rides_tbl2 (
	`Booking_ID` TEXT,
	`Booking_Status` TEXT,
	`Customer_ID` TEXT,
	`Vehicle_Type` TEXT,
	`Pickup_Location` TEXT,
	`Drop_Location` TEXT,
	`V_TAT` FLOAT(53),
	`C_TAT` FLOAT(53),
	`Canceled_Rides_by_Customer` TEXT,
	`Canceled_Rides_by_Driver` TEXT,
	`Incomplete_Rides` TEXT,
	`Incomplete_Rides_Reason` TEXT,
	`Booking_Value` BIGINT,
	`Payment_Method` TEXT,
	`Ride_Distance` BIGINT,
	`Driver_Ratings` FLOAT(53),
	`Customer_Rating` FLOAT(53),
	`Vehicle Images` TEXT,
	`Timestamp` TEXT,
	`Hour_of_Day` BIGINT,
	`Day_of_Week` TEXT,
	`Month` TEXT,
	`Day_of_Month` BIGINT,
	`Weekday_Weekend` TEXT,
	`Is_Canceled` BOOL,
	`Is_Customer_Canceled` BOOL,
	`Is_Driver_Canceled` BOOL,
	`Is_Incomplete` BOOL
)


2025-07-17 00:34:35,796 INFO sqlalchemy.engine.Engine [no key 0.00081s] {}
2025-07-17 00:34:36,982 INFO sqlalchemy.engine.Engine INSERT INTO ola_rides_tbl2 (`Booking_ID`, `Booking_Status`, `Customer_ID`, `Vehicle_Type`, `Pickup_Location`, `Drop_Location`, `V_TAT`, `C_TAT`, `Canceled_Rides_by_Customer`, `Canceled_Rides_by_Driver`, `Incomplete_Rides`, `Incomplete_Rides_Reason`, `Booking_Value`, `Payment_Method`, `Ride_Distance`, `Driver_Ratings`, `Customer_Rating`, `Vehicle Images`, `Timestamp`, `Hour_of_Day`, `Day_of_Week`, `Month`, `Day_of_Month`, `Weekday_Weekend`, `Is_Canceled`, `Is_Customer_Canceled`, `Is_Driver_Canceled`, `Is_Incomplete`) VALUES (%(Booking_ID)s, %(Booking_Status)s, %(Customer_ID)s, %(Vehicle_Type)s, %(Pickup_Location)s, %(Drop_Location)s, %(V_TAT)s, %(C_TAT)s, %(Canceled_Rides_by_Customer)s, %(Canceled_Rides_by_Driver)s, %(Incomplete_Rides)s, %(Incomplete_Rides_Reason)s, %(Booking_Value)s, %(Payment_Method)s, %(Ride_Distance)s, %(Driver_Ratings)s, %(Customer_Rating)s, %(Vehicle_Images)s, %(Timestamp)s, %(Hour_of_Day)s, %(Day_of_Week)s, %(Month)s, %(Day_of_Month)s, %(Weekday_Weekend)s, %(Is_Canceled)s, %(Is_Customer_Canceled)s, %(Is_Driver_Canceled)s, %(Is_Incomplete)s)
2025-07-17 00:34:36,982 INFO sqlalchemy.engine.Engine [generated in 0.94218s] [{'Booking_ID': 'CNR7153255142', 'Booking_Status': 'Canceled by Driver', 'Customer_ID': 'CID713523', 'Vehicle_Type': 'Prime Sedan', 'Pickup_Location': 'Tumkur Road', 'Drop_Location': 'RT Nagar', 'V_TAT': None, 'C_TAT': None, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Personal & Car related issue', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 444, 'Payment_Method': 'Unknown', 'Ride_Distance': 0, 'Driver_Ratings': None, 'Customer_Rating': None, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/14183/14183770.png', 'Timestamp': '2024-07-26 14:00:00', 'Hour_of_Day': 14, 'Day_of_Week': 'Friday', 'Month': 'July', 'Day_of_Month': 26, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 1, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 1, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR2940424040', 'Booking_Status': 'Success', 'Customer_ID': 'CID225428', 'Vehicle_Type': 'Bike', 'Pickup_Location': 'Magadi Road', 'Drop_Location': 'Varthur', 'V_TAT': 203.0, 'C_TAT': 30.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 158, 'Payment_Method': 'Cash', 'Ride_Distance': 13, 'Driver_Ratings': 4.1, 'Customer_Rating': 4.0, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/9983/9983173.png', 'Timestamp': '2024-07-25 22:20:00', 'Hour_of_Day': 22, 'Day_of_Week': 'Thursday', 'Month': 'July', 'Day_of_Month': 25, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR2982357879', 'Booking_Status': 'Success', 'Customer_ID': 'CID270156', 'Vehicle_Type': 'Prime SUV', 'Pickup_Location': 'Sahakar Nagar', 'Drop_Location': 'Varthur', 'V_TAT': 238.0, 'C_TAT': 130.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 386, 'Payment_Method': 'UPI', 'Ride_Distance': 40, 'Driver_Ratings': 4.2, 'Customer_Rating': 4.8, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/9983/9983204.png', 'Timestamp': '2024-07-30 19:59:00', 'Hour_of_Day': 19, 'Day_of_Week': 'Tuesday', 'Month': 'July', 'Day_of_Month': 30, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR2395710036', 'Booking_Status': 'Canceled by Customer', 'Customer_ID': 'CID581320', 'Vehicle_Type': 'eBike', 'Pickup_Location': 'HSR Layout', 'Drop_Location': 'Vijayanagar', 'V_TAT': None, 'C_TAT': None, 'Canceled_Rides_by_Customer': 'Driver is not moving towards pickup location', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 384, 'Payment_Method': 'Unknown', 'Ride_Distance': 0, 'Driver_Ratings': None, 'Customer_Rating': None, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/6839/6839867.png', 'Timestamp': '2024-07-22 03:15:00', 'Hour_of_Day': 3, 'Day_of_Week': 'Monday', 'Month': 'July', 'Day_of_Month': 22, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 1, 'Is_Customer_Canceled': 1, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR1797421769', 'Booking_Status': 'Success', 'Customer_ID': 'CID939555', 'Vehicle_Type': 'Mini', 'Pickup_Location': 'Rajajinagar', 'Drop_Location': 'Chamarajpet', 'V_TAT': 252.0, 'C_TAT': 80.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 822, 'Payment_Method': 'Credit Card', 'Ride_Distance': 45, 'Driver_Ratings': 4.0, 'Customer_Rating': 3.0, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/3202/3202926.png', 'Timestamp': '2024-07-02 09:02:00', 'Hour_of_Day': 9, 'Day_of_Week': 'Tuesday', 'Month': 'July', 'Day_of_Month': 2, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR8787177882', 'Booking_Status': 'Success', 'Customer_ID': 'CID802429', 'Vehicle_Type': 'Mini', 'Pickup_Location': 'Kadugodi', 'Drop_Location': 'Vijayanagar', 'V_TAT': 231.0, 'C_TAT': 90.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 173, 'Payment_Method': 'UPI', 'Ride_Distance': 41, 'Driver_Ratings': 3.4, 'Customer_Rating': 4.6, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/3202/3202926.png', 'Timestamp': '2024-07-13 04:42:00', 'Hour_of_Day': 4, 'Day_of_Week': 'Saturday', 'Month': 'July', 'Day_of_Month': 13, 'Weekday_Weekend': 'Weekend', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR3612067560', 'Booking_Status': 'Success', 'Customer_ID': 'CID476071', 'Vehicle_Type': 'Bike', 'Pickup_Location': 'Tumkur Road', 'Drop_Location': 'Whitefield', 'V_TAT': 133.0, 'C_TAT': 40.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 140, 'Payment_Method': 'Cash', 'Ride_Distance': 49, 'Driver_Ratings': 3.2, 'Customer_Rating': 4.5, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/9983/9983173.png', 'Timestamp': '2024-07-23 09:51:00', 'Hour_of_Day': 9, 'Day_of_Week': 'Tuesday', 'Month': 'July', 'Day_of_Month': 23, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR5374902489', 'Booking_Status': 'Canceled by Driver', 'Customer_ID': 'CID735691', 'Vehicle_Type': 'Prime Plus', 'Pickup_Location': 'Bannerghatta Road', 'Drop_Location': 'Sarjapur Road', 'V_TAT': None, 'C_TAT': None, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Personal & Car related issue', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 344, 'Payment_Method': 'Unknown', 'Ride_Distance': 0, 'Driver_Ratings': None, 'Customer_Rating': None, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/11409/11409716.png', 'Timestamp': '2024-07-11 11:12:00', 'Hour_of_Day': 11, 'Day_of_Week': 'Thursday', 'Month': 'July', 'Day_of_Month': 11, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 1, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 1, 'Is_Incomplete': 0}  ... displaying 10 of 103024 total bound parameter sets ...  {'Booking_ID': 'CNR2027162035', 'Booking_Status': 'Success', 'Customer_ID': 'CID118301', 'Vehicle_Type': 'eBike', 'Pickup_Location': 'Indiranagar', 'Drop_Location': 'Magadi Road', 'V_TAT': 210.0, 'C_TAT': 140.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 267, 'Payment_Method': 'UPI', 'Ride_Distance': 47, 'Driver_Ratings': 3.4, 'Customer_Rating': 3.1, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/6839/6839867.png', 'Timestamp': '2024-07-31 14:56:00', 'Hour_of_Day': 14, 'Day_of_Week': 'Wednesday', 'Month': 'July', 'Day_of_Month': 31, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}, {'Booking_ID': 'CNR9770709721', 'Booking_Status': 'Success', 'Customer_ID': 'CID217959', 'Vehicle_Type': 'Auto', 'Pickup_Location': 'Ulsoor', 'Drop_Location': 'Hennur', 'V_TAT': 175.0, 'C_TAT': 125.0, 'Canceled_Rides_by_Customer': 'Not Canceled by Customer', 'Canceled_Rides_by_Driver': 'Not Canceled by Driver', 'Incomplete_Rides': 'No', 'Incomplete_Rides_Reason': 'Not Incomplete', 'Booking_Value': 462, 'Payment_Method': 'UPI', 'Ride_Distance': 3, 'Driver_Ratings': 4.8, 'Customer_Rating': 4.4, 'Vehicle_Images': 'https://cdn-icons-png.flaticon.com/128/16526/16526595.png', 'Timestamp': '2024-07-31 13:57:00', 'Hour_of_Day': 13, 'Day_of_Week': 'Wednesday', 'Month': 'July', 'Day_of_Month': 31, 'Weekday_Weekend': 'Weekday', 'Is_Canceled': 0, 'Is_Customer_Canceled': 0, 'Is_Driver_Canceled': 0, 'Is_Incomplete': 0}]
2025-07-17 00:34:40,979 INFO sqlalchemy.engine.Engine COMMIT

103024